// clients/manage-client-vue/src/views/Login.vue
<template>
  <div class="login-container">
    <el-card class="login-card">
      <h2 class="login-title">用户登录</h2>
      <el-form @submit.prevent="handleLogin">
        <el-form-item>
          <el-input
            v-model="loginForm.username"
            placeholder="请输入用户名"
            prefix-icon="User"
          />
        </el-form-item>
        
        <el-form-item>
          <el-input
            v-model="loginForm.password"
            type="password"
            placeholder="请输入密码"
            prefix-icon="Lock"
            show-password
          />
        </el-form-item>
        
        <el-form-item class="action-buttons">
          <el-button type="primary" native-type="submit">登录</el-button>
          <el-button type="info" @click="handleRegister">注册</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { ElMessage } from 'element-plus'

const loginForm = ref({
  username: '',
  password: ''
})

const handleLogin = () => {
  console.log('登录信息:', {
    username: loginForm.value.username,
    password: loginForm.value.password
  })
  ElMessage.success('登录成功')
}

const handleRegister = () => {
  console.log('注册信息:', {
    username: loginForm.value.username,
    password: loginForm.value.password
  })
  ElMessage.success('注册成功')
}
</script>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background-color: #f5f5f5;
}

.login-card {
  width: 400px;
  padding: 20px;
}

.login-title {
  text-align: center;
  margin-bottom: 30px;
  color: #333;
}

.action-buttons {
  display: flex;
  gap: 12px;
}

.action-buttons .el-button {
  flex: 1;
}
</style>

// manage-client-react-js/src/components/Login.jsx
import {Button, Form, Input, Space} from 'antd'
import React, {useState} from 'react'

const Login = () => {
    // 定义状态用于存储用户名和密码
    const [username, setUsername] = useState('')
    const [password, setPassword] = useState('')

    // 登录按钮的点击事件处理函数
    const handleLogin = () => {
        console.log('用户名:', username)
        console.log('密码:', password)
    }

    return (
        <div style={{width: 300, margin: '50px auto'}}>
            <h2 style={{color: '#FFA500', textAlign: 'center'}}>登录</h2>
            <Form>
                <Form.Item>
                    <Input placeholder='请输入用户名' value={username} onChange={e => setUsername(e.target.value)} />
                </Form.Item>
                <Form.Item>
                    <Input.Password placeholder='请输入密码' value={password} onChange={e => setPassword(e.target.value)} />
                </Form.Item>
                <Form.Item>
                    <Space>
                        <Button type='primary' onClick={handleLogin}>
                            登录
                        </Button>
                        <Button type='primary' onClick={() => console.log('游客登录！')}>
                            游客登录
                        </Button>
                    </Space>
                </Form.Item>
            </Form>
        </div>
    )
}

export default Login
